export const CAR_MAKES = [
  "Acura", "Alfa Romeo", "Aston Martin", "Audi",
  "Bentley", "BMW", "BYD", "Buick",
  "Cadillac", "Changan", "Chery", "Chevrolet", "Chrysler", "Citroën",
  "Dodge", "DS",
  "Ferrari", "Fiat", "Ford",
  "GAC", "Geely", "Genesis", "GMC", "Great Wall",
  "Haval", "Honda", "Hongqi", "Hyundai",
  "Infiniti", "Isuzu",
  "Jaguar", "Jeep",
  "Kia",
  "Lamborghini", "Land Rover", "Lexus", "Lincoln", "Lotus", "Lucid",
  "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "MG", "Mini", "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot", "Polestar", "Porsche", "Proton",
  "RAM", "Renault", "Rivian", "Rolls-Royce",
  "Saab", "Seat", "Škoda", "Smart", "SsangYong", "Subaru", "Suzuki",
  "Tank", "Tesla", "Toyota",
  "Volkswagen", "Volvo",
  "Wuling",
  "Zeekr",
] as const;

export const CAR_MODELS: Record<string, string[]> = {
  "Acura":          ["ILX", "Integra", "MDX", "RDX", "TLX"],
  "Alfa Romeo":     ["Giulia", "Stelvio", "Tonale"],
  "Aston Martin":   ["DB11", "DB12", "DBX", "Vantage"],
  "Audi":           ["A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "e-tron GT", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "RS3", "RS5", "RS6", "RS7", "S3", "S4", "S5", "TT"],
  "Bentley":        ["Bentayga", "Continental GT", "Flying Spur"],
  "BMW":            ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "i4", "i5", "i7", "iX", "iX1", "iX3", "M2", "M3", "M4", "M5", "M8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z4"],
  "BYD":            ["Atto 3", "Dolphin", "Han", "Seal", "Song Plus", "Tang", "Yuan Plus"],
  "Buick":          ["Enclave", "Encore", "Encore GX", "Envision"],
  "Cadillac":       ["CT4", "CT5", "Escalade", "Lyriq", "XT4", "XT5", "XT6"],
  "Changan":        ["CS35 Plus", "CS55 Plus", "CS75 Plus", "Eado Plus", "Uni-K", "Uni-T", "Uni-V"],
  "Chery":          ["Arrizo 6", "Tiggo 2 Pro", "Tiggo 4 Pro", "Tiggo 7 Pro", "Tiggo 8 Pro"],
  "Chevrolet":      ["Blazer", "Camaro", "Colorado", "Corvette", "Equinox", "Malibu", "Silverado", "Suburban", "Tahoe", "Traverse", "Trax"],
  "Chrysler":       ["300", "Pacifica"],
  "Citroën":        ["Berlingo", "C3", "C4", "C5 Aircross", "C5 X"],
  "Dodge":          ["Challenger", "Charger", "Durango", "Hornet"],
  "DS":             ["DS 3", "DS 4", "DS 7", "DS 9"],
  "Ferrari":        ["296 GTB", "812", "F8", "Purosangue", "Roma", "SF90"],
  "Fiat":           ["500", "500X", "Panda", "Tipo"],
  "Ford":           ["Bronco", "Edge", "Escape", "Expedition", "Explorer", "F-150", "Maverick", "Mustang", "Ranger", "Territory"],
  "GAC":            ["Emkoo", "Empow", "GS3", "GS4", "GS8"],
  "Geely":          ["Azkarra", "Coolray", "Emgrand", "Monjaro", "Okavango", "Starray"],
  "Genesis":        ["Electrified G80", "Electrified GV70", "G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GMC":            ["Acadia", "Canyon", "Hummer EV", "Sierra", "Terrain", "Yukon"],
  "Great Wall":     ["Poer", "Tank 300", "Tank 500", "Wingle"],
  "Haval":          ["Dargo", "H6", "H9", "Jolion"],
  "Honda":          ["Accord", "City", "Civic", "CR-V", "HR-V", "Pilot", "ZR-V"],
  "Hongqi":         ["E-HS9", "H5", "H9", "HS5"],
  "Hyundai":        ["Accent", "Creta", "Elantra", "i10", "i20", "i30", "Ioniq 5", "Ioniq 6", "Kona", "Palisade", "Santa Fe", "Sonata", "Staria", "Tucson", "Venue"],
  "Infiniti":       ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  "Isuzu":          ["D-Max", "MU-X"],
  "Jaguar":         ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF"],
  "Jeep":           ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  "Kia":            ["Carnival", "Cerato", "EV6", "EV9", "K5", "Niro", "Pegas", "Picanto", "Rio", "Seltos", "Sorento", "Sportage", "Stinger", "Telluride"],
  "Lamborghini":    ["Huracán", "Revuelto", "Urus"],
  "Land Rover":     ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus":          ["ES", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "RZ", "TX", "UX"],
  "Lincoln":        ["Aviator", "Corsair", "Navigator", "Nautilus"],
  "Lotus":          ["Eletre", "Emira", "Evija"],
  "Lucid":          ["Air"],
  "Maserati":       ["Ghibli", "Granturismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Mazda":          ["CX-3", "CX-30", "CX-5", "CX-50", "CX-60", "CX-9", "CX-90", "Mazda3", "Mazda6", "MX-5", "MX-30"],
  "McLaren":        ["720S", "750S", "Artura", "GT"],
  "Mercedes-Benz":  ["A-Class", "AMG GT", "B-Class", "C-Class", "CLA", "CLE", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "Maybach", "S-Class", "SL", "Sprinter", "V-Class", "Vito"],
  "MG":             ["4", "5", "HS", "Marvel R", "MG3", "ZS", "ZS EV"],
  "Mini":           ["Clubman", "Convertible", "Cooper", "Countryman", "Electric"],
  "Mitsubishi":     ["ASX", "Eclipse Cross", "L200", "Outlander", "Pajero", "Xpander"],
  "Nissan":         ["Altima", "Ariya", "Frontier", "Juke", "Kicks", "Leaf", "Maxima", "Navara", "Note", "Pathfinder", "Patrol", "Qashqai", "Rogue", "Sentra", "Sunny", "Titan", "X-Trail", "Z"],
  "Opel":           ["Astra", "Corsa", "Crossland", "Grandland", "Mokka"],
  "Peugeot":        ["2008", "208", "3008", "308", "408", "5008", "508", "Landtrek", "Partner", "Rifter"],
  "Polestar":       ["Polestar 2", "Polestar 3", "Polestar 4"],
  "Porsche":        ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Proton":         ["Iriz", "Persona", "Saga", "X50", "X70", "X90"],
  "RAM":            ["1500", "2500", "3500"],
  "Renault":        ["Arkana", "Captur", "Clio", "Duster", "Kadjar", "Koleos", "Megane", "Talisman"],
  "Rivian":         ["R1S", "R1T"],
  "Rolls-Royce":    ["Cullinan", "Ghost", "Phantom", "Spectre", "Wraith"],
  "Saab":           ["9-3", "9-5"],
  "Seat":           ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco"],
  "Škoda":          ["Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Scala", "Superb"],
  "Smart":          ["#1", "#3", "EQ fortwo"],
  "SsangYong":      ["Korando", "Musso", "Rexton", "Tivoli", "Torres"],
  "Subaru":         ["BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "WRX"],
  "Suzuki":         ["Baleno", "Celerio", "Ertiga", "Grand Vitara", "Jimny", "S-Cross", "Swift", "Vitara", "XL7"],
  "Tank":           ["300", "500"],
  "Tesla":          ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  "Toyota":         ["4Runner", "86", "Avalon", "C-HR", "Camry", "Corolla", "Corolla Cross", "Fortuner", "GR Supra", "GR86", "Highlander", "Hilux", "Land Cruiser", "Prado", "Prius", "RAV4", "Rush", "Sequoia", "Tacoma", "Tundra", "Veloz", "Yaris", "Yaris Cross"],
  "Volkswagen":     ["Amarok", "Arteon", "Atlas", "Caddy", "Golf", "ID.3", "ID.4", "ID.5", "ID.Buzz", "Jetta", "Passat", "Polo", "T-Cross", "T-Roc", "Taos", "Teramont", "Tiguan", "Touareg", "Transporter"],
  "Volvo":          ["C40", "EX30", "EX90", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
  "Wuling":         ["Almaz", "Alvez", "Air EV", "Confero", "Cortez"],
  "Zeekr":          ["001", "007", "009", "X"],
};

export const CAR_COLORS = [
  "White", "Pearl White", "Off White",
  "Black", "Midnight Black",
  "Silver", "Grey", "Dark Grey",
  "Red", "Maroon", "Burgundy",
  "Blue", "Navy Blue", "Sky Blue",
  "Green", "Dark Green",
  "Brown", "Bronze", "Beige", "Champagne",
  "Gold", "Orange", "Yellow", "Cream", "Pink", "Purple",
];

export function getYearOptions(): string[] {
  const currentYear = new Date().getFullYear() + 1;
  const years: string[] = [];
  for (let y = currentYear; y >= 1980; y--) {
    years.push(String(y));
  }
  return years;
}
